services:
  imbeddings:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: imbeddings
    container_name: imbeddings
    environment:
      HF_TOKEN: ${HF_TOKEN:?HF_TOKEN is required}
    ports:
      - "${IMBEDDINGS_PORT:-8000}:${IMBEDDINGS_PORT:-8000}"
    volumes:
      - hf-cache:/root/.cache/huggingface

volumes:
  hf-cache:
